# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes)
names:
  0: Brown Bandicoot
  1: Brush-tailed Rock-wallaby
  2: Brushtail Possum
  3: Cat
  4: Cervid Deer
  5: Common Wombat
  6: Dog
  7: Eastern Grey Kangaroo
  8: Echidna
  9: Emu
  10: Euro
  11: Fallow Deer
  12: Goat
  13: Horse
  14: Koala
  15: Long-nosed Bandicoot
  16: Pig
  17: Rabbit Hare
  18: Rat
  19: Red Fox
  20: Red-legged Pademelon
  21: Red-necked Pademelon
  22: Red-necked Wallaby
  23: Spotted-tailed Quoll
  24: Superb Lyrebird
  25: Swamp Wallaby